# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main  # Set your default branch here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set your JDK version here
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: project-405004

      - name: Deploy to Google App Engine
        run: |
          gcloud config set project project-405004
          gcloud app deploy app.yaml
